import 'package:flutter/material.dart';

class TwoFactorAuth extends StatefulWidget {
  const TwoFactorAuth({Key? key}) : super(key: key);

  @override
  State<TwoFactorAuth> createState() => _TwoFactorAuthState();
}

bool off_here = false;
bool off_too = false;

class _TwoFactorAuthState extends State<TwoFactorAuth> {
  @override
  Widget build(BuildContext context) {
    void switchToggle(bool value) {
      if (off_here == false) {
        setState(() {
          off_here = true;
        });
      } else {
        setState(() {
          off_here = false;
        });
      }
    }

    return Container(
      height: 366,
      color: Colors.white,
      child: Column(
        children: [
          Padding(
            padding: const EdgeInsets.only(left: 20, top: 15),
            child: Row(
              children: const [
                Text(
                  "Two-step verification options",
                  style: TextStyle(fontSize: 17, fontWeight: FontWeight.bold),
                ),
                SizedBox(
                  width: 100,
                ),
                Icon(Icons.settings)
              ],
            ),
          ),
          const Padding(
            padding: EdgeInsets.only(left: 20, right: 20, top: 20),
            child: Text(
              "Add an extra layer of security to block unauthorized access and protect your account.",
              style: TextStyle(fontSize: 16),
            ),
          ),
          const Divider(
            color: Color.fromARGB(255, 202, 200, 200),
          ),
          ListTile(
            title: Row(
              children: const [
                Text(
                  "Authenticator app mode",
                  style: TextStyle(fontSize: 17, fontWeight: FontWeight.bold),
                ),
                Icon(
                  Icons.question_mark_rounded,
                  size: 15,
                  color: Colors.green,
                )
              ],
            ),
            // leading: Icon(Icons.question_mark),
            trailing: Switch(
              value: off_too,
              onChanged: switchToggle,
              activeColor: Colors.green,
            ),
            subtitle: const Text("(Recommended)"),
          ),
          const ListTile(
            leading: Icon(
              Icons.check_circle,
              color: Colors.grey,
            ),
            title: Text("Disabled"),
            subtitle: Text(
                "Enter a code generated by your authenticator app to confirm its you."),
          ),
          const Divider(
            color: Color.fromARGB(255, 202, 200, 200),
          ),
          const SizedBox(
            height: 0,
          ),
          ListTile(
            leading: const SizedBox(
              width: 10,
            ),
            title: Row(
              children: const [
                Text(
                  "Text Message",
                ),
                Icon(
                  Icons.question_mark_rounded,
                  size: 15,
                  color: Colors.green,
                )
              ],
            ),
            subtitle: const Text(
                "Receive a six digit code by text message to confirm its you."),
          ),
        ],
      ),
    );
  }
}
